### ISSUE TITLE
main_dev.sh: No such file

### ISSUE THREAD

**Issue by linas** [hansonrobotics/hrtool#10]
when I say `hr run`  I get the following error:

```
/usr/bin/hr: kine 849: ./main_dev.sh: No such file or directory
```

I am able to work around this by saying: 
```
ln -s ~/hansonrobotics/launchpad/main.sh ~/hansonrobotics/launchpad/main_dev.sh 
```

but I'm not sure if this work-around it correct.

**Comment by wenwei-dev** [comment]
Thanks. This is the right workaround.
