### ISSUE TITLE
install head-hr-ext fails

### ISSUE THREAD

**Issue by tomsepe** [hansonrobotics/hrtool#37]
nothing happens when I run this:
`source ~/.bashrc && hr cmd get_latest_version hansonrobotics/hrtool-ext`

and  runining
`hr install head-hr-extInstalling head-hr-ext`
fails:
 ```
No version is found for repo "hansonrobotics/hrtool-ext"
Install head-hr-ext FAILED, return code 1
```

I was able to fix this by exluding the '-ext' & running:
source ~/.bashrc && hr cmd get_latest_version hansonrobotics/hrtool

and by modifying hr-base
changed line 1607
from:
`    local repo=hansonrobotics/hrtool-ext
`
to:
`    local repo=hansonrobotics/hrtool
`

**Comment by wenwei-dev** [comment]
Sorry, this extension is not open to the public.
