### ISSUE TITLE
head-python-emopy not installed with hr install

### ISSUE THREAD

**Issue by eddiemonroe** [hansonrobotics/hrtool#5]
I followed the directions in the Guide to Move to New HEAD document.
$ hr install

...
Unpacking head-ros-emotion (0.1.0) ...
dpkg: dependency problems prevent configuration of head-ros-emotion:
 head-ros-emotion depends on head-python-emopy; however:
  Package head-python-emopy is not installed.

dpkg: error processing package head-ros-emotion (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 head-ros-emotion

I was able to install manually with
$ hr install head-python-emopy
but looks like it didn't get installed with the main install script.

**Comment by wenwei-dev** [comment]
Can you show me the output of `hr version`? And the errors of command `hr install head-python-emopy`

**Comment by eddiemonroe** [comment]
eddie@eddie-Gazelle:~$ hr version
head-asr=0.2.0
head-basic-head-api=0.1.0
head-blender-api=0.1.2
head-blender-api-msgs=0.3.0
head-cereproc=4.0.1
head-chatbot=0.1.2
head-chatscript=7.5.2
head-chatscript-han=1.0.2
head-chatscript-sophia=1.0.2
head-data=0.1.0
head-deps-all=0.1.2
head-dynamixel-motor=0.4.0
head-festival-api=0.1.6
head-hr=0.8.6
head-hr-ext=0.6.4
head-hr-msgs=0.0.1
head-marky-markov=0.3.6
head-motors-safety=0.1.0
head-pau2motors=0.1.2
head-perception=0.0.2
head-performances=0.0.3
head-pi-vision=0.3.1
head-pocketsphinx=1.0.1
head-python-emopy=0.1.1
head-python-hr-characters=0.1.1
head-python-iflytek=0.1.0
head-python-pololu-motors=0.2.1
head-python-ttsserver=0.2.2
head-realsense-ros=0.0.1-1
head-ros-emotion=0.1.0
head-ros-misc=0.1.2
head-ros-pololu=0.1.0
head-ros-tts=0.2.1
head-saliency-tracker=0.1.0
head-sophia-blender-api=1.0.2
head-sound=0.1.1
head-sphinxbase=1.0.1
head-ttsserver-voice-api=0.1.4
head-webui=0.0.5

> And the errors of command hr install head-python-emopy

I was able to successfully install using the above command, no errors. I was meaning previously that it looks like head-python-emopy did not get installed via the hr install head command.

**Comment by linas** [comment]
Closing, I believe this is now fixed.
